(executable
 (name test)
 (public_name Test)
 (modules test)
 (libraries Language ounit2 str))

(test
 (name compiler_tests)
 (modules compiler_tests)
 (libraries Language ounit2 unix)
 (deps (source_tree compiler_cases))
 (action
  (chdir %{workspace_root} (run %{test}))))

(test
 (name hover_ident_tests)
 (modules hover_ident_tests)
 (libraries Language ounit2)
 (action (chdir %{workspace_root} (run %{test}))))

(test
 (name repl_trait_impl_tests)
 (modules repl_trait_impl_tests)
 (libraries Language ounit2)
 (action (chdir %{workspace_root} (run %{test}))))

(test
 (name trait_impl_program_tests)
 (modules trait_impl_program_tests)
 (libraries Language ounit2)
 (action (chdir %{workspace_root} (run %{test}))))

(test
 (name trait_impl_massive_tests)
 (modules trait_impl_massive_tests)
 (libraries Language ounit2)
 (action (chdir %{workspace_root} (run %{test}))))

(test
 (name repl_format_constraints_massive_tests)
 (modules repl_format_constraints_massive_tests)
 (libraries Language ounit2)
 (action (chdir %{workspace_root} (run %{test}))))
