(rule
 (target prelude_data.ml)
 (deps
  (:gen %{workspace_root}/scripts/gen_prelude_data_ml.bash)
  (:prelude %{workspace_root}/prelude/prelude.ls))
 (action
  (run bash %{gen} %{target} %{prelude})))

(executable
 (name forge_browser)
 (modes js)
 (libraries js_of_ocaml language)
 (modules forge_browser prelude_data))
