; Generated by LambdaScript compiler (Min_ir → LLVM IR)
source_filename = "lambdascript"

%ls.clos = type { i8*, i8* }

declare void @ls_print(i8*)
declare void @ls_println(i8*)
declare void @ls_abort()
declare i8* @ls_int_to_str(i32)
declare i8* @ls_str_concat(i8*, i8*)
declare i32 @strcmp(i8*, i8*)
declare i8* @ls_malloc(i64)
declare i8* @ls_mkclos(i8*, i8*)

define i32 @main() {
entry:
  %_t1 = and i1 false, false
  br i1 %_t1, label %then_1, label %else_2
then_1:
  br label %merge_3
merge_3:
  %_t2 = phi i32 [ 1, %then_1 ], [ 0, %else_2 ]
  %_t3 = call i8* @ls_int_to_str(i32 %_t2)
  call void @ls_println(i8* %_t3)
  ret i32 0
else_2:
  br label %merge_3
}
