; Generated by LambdaScript compiler (Min_ir → LLVM IR)
source_filename = "lambdascript"

%ls.clos = type { i8*, i8* }

declare void @ls_print(i8*)
declare void @ls_println(i8*)
declare void @ls_abort()
declare i8* @ls_int_to_str(i32)
declare i8* @ls_str_concat(i8*, i8*)
declare i32 @strcmp(i8*, i8*)
declare i8* @ls_malloc(i64)
declare i8* @ls_mkclos(i8*, i8*)

define i32 @lam__lsn1(i32 %y) {
entry:
  %_t1 = add nsw i32 %y, 1
  ret i32 %_t1
}

define i32 @main() {
entry:
  %_t2 = call i8* @ls_int_to_str(i32 4)
  call void @ls_println(i8* %_t2)
  ret i32 0
}
