#!/usr/bin/env bash
set -euo pipefail
# Usage: gen_prelude_data_ml.bash <output.ml> <prelude.ls>
out="$1"
prelude="$2"
{
  printf '%s\n' '(* Generated by scripts/gen_prelude_data_ml.bash — do not edit. *)'
  printf '%s\n' 'let prelude_ls = {prelude|'
  cat "$prelude"
  printf '\n|prelude}\n'
} > "$out"
