(** Emit LLVM IR text from {!Min_ir.prog}. Link with [runtime/ls_runtime.c] using
    [clang]. Runtime: [ls_print], [ls_println], [ls_int_to_str]. *)

open Min_ir

type emit_ctx = {
  mutable prelude : string list;
  mutable str_counter : int;
}

let ctx_create () = { prelude = []; str_counter = 0 }

let llvm_ll_ty : ty -> string = function
  | I32 -> "i32"
  | I1 -> "i1"
  | String -> "i8*"
  | Unit -> "void"

let ibin_ll : ibin -> string = function
  | Add -> "add nsw"
  | Sub -> "sub nsw"
  | Mul -> "mul nsw"
  | Div -> "sdiv"
  | Mod -> "srem"

let icmp_ll : icmp -> string = function
  | Eq -> "eq"
  | Ne -> "ne"
  | Ult -> "ult"
  | Slt -> "slt"

let callee_ll : string -> string = function
  | "print" -> "ls_print"
  | "println" -> "ls_println"
  | "int_to_str" -> "ls_int_to_str"
  | n -> n

let llvm_c_escape s =
  let b = Buffer.create (String.length s * 2) in
  String.iter
    (fun c ->
      match c with
      | '\"' -> Buffer.add_string b "\\22"
      | '\\' -> Buffer.add_string b "\\5C"
      | '\n' -> Buffer.add_string b "\\0A"
      | '\t' -> Buffer.add_string b "\\09"
      | '\r' -> Buffer.add_string b "\\0D"
      | c when Char.code c < 32 || Char.code c > 126 ->
          Printf.bprintf b "\\%02X" (Char.code c)
      | c -> Buffer.add_char b c)
    s;
  Buffer.contents b

let term_succs (t : term) : string list =
  match t with Ret _ -> [] | Br l -> [ l ] | BrCond (_, l1, l2) -> [ l1; l2 ]

let ordered_blocks (entry : string) (blocks : (string * block) list) : block list
    =
  let tbl : (string, block) Hashtbl.t = Hashtbl.create 16 in
  List.iter (fun (l, b) -> Hashtbl.add tbl l b) blocks;
  let visited : (string, unit) Hashtbl.t = Hashtbl.create 16 in
  let out = ref [] in
  let rec visit lbl =
    if Hashtbl.mem visited lbl then ()
    else (
      Hashtbl.replace visited lbl ();
      let blk = Hashtbl.find tbl lbl in
      out := !out @ [ blk ];
      List.iter visit (term_succs blk.term))
  in
  visit entry;
  List.iter
    (fun (l, blk) ->
      if not (Hashtbl.mem visited l) then (
        Hashtbl.replace visited l ();
        out := !out @ [ blk ]))
    blocks;
  !out

let runtime_declarations : string =
  "declare void @ls_print(i8*)\n\
   declare void @ls_println(i8*)\n\
   declare i8* @ls_int_to_str(i32)\n"

let module_banner =
  "; Generated by LambdaScript compiler (Min_ir → LLVM IR)\n\
   source_filename = \"lambdascript\"\n\n"

module H = Hashtbl

let emit_global_string ctx (dst : string) (s : string) : string =
  let idx = ctx.str_counter in
  ctx.str_counter <- idx + 1;
  let lit = llvm_c_escape s in
  let n = String.length s + 1 in
  let gname = Printf.sprintf ".str.%d" idx in
  let line =
    Printf.sprintf "@%s = private unnamed_addr constant [%d x i8] c\"%s\\00\""
      gname n lit
  in
  ctx.prelude <- line :: ctx.prelude;
  Printf.sprintf
    "  %%%s = getelementptr inbounds ([%d x i8], [%d x i8]* @%s, i64 0, i64 0)"
    dst n n gname

let operand_min_ty (h : (string, ty) H.t) : operand -> ty = function
  | ConstI32 _ -> I32
  | ConstI1 _ -> I1
  | ConstStr _ -> String
  | ConstUnit -> Unit
  | Local x -> (
      match H.find_opt h x with
      | Some t -> t
      | None -> failwith ("llvm_emit: unknown local " ^ x))

let emit_operand h (op : operand) : string * string =
  match op with
  | ConstI32 n -> ("i32", string_of_int n)
  | ConstI1 b -> ("i1", if b then "true" else "false")
  | ConstStr _ -> failwith "llvm_emit: ConstStr must use Copy/global"
  | ConstUnit -> failwith "llvm_emit: ConstUnit in value position"
  | Local x -> (llvm_ll_ty (H.find h x), "%" ^ x)

let rhs_result_ty h : rhs -> ty = function
  | Copy o -> operand_min_ty h o
  | Binop _ -> I32
  | ICmp _ -> I1
  | Call ("int_to_str", _) -> String
  | Call _ -> failwith "llvm_emit: unsupported callee"

let emit_copy_dst ctx h lines dst o =
  match o with
  | ConstStr s ->
      lines := !lines @ [ emit_global_string ctx dst s ];
      H.replace h dst String
  | ConstI32 _ | ConstI1 _ ->
      let t, v = emit_operand h o in
      let ins =
        if t = "i32" then Printf.sprintf "  %%%s = add nsw i32 %s, 0" dst v
        else Printf.sprintf "  %%%s = xor i1 %s, false" dst v
      in
      lines := !lines @ [ ins ];
      H.replace h dst (operand_min_ty h o)
  | Local _ ->
      let t, v = emit_operand h o in
      let ins =
        if t = "i32" then Printf.sprintf "  %%%s = add nsw i32 %s, 0" dst v
        else if t = "i1" then Printf.sprintf "  %%%s = xor i1 %s, false" dst v
        else if t = "i8*" then Printf.sprintf "  %%%s = bitcast i8* %s to i8*" dst v
        else failwith "llvm_emit: copy"
      in
      lines := !lines @ [ ins ];
      H.replace h dst (operand_min_ty h o)
  | ConstUnit -> failwith "llvm_emit: copy unit"

let emit_instr ctx (h : (string, ty) H.t) (lines : string list ref)
    (instr : instr) : unit =
  match instr with
  | Phi _ ->
      failwith "llvm_emit: phi not implemented (add when lowering uses branches)"
  | VoidCall (name, args) -> (
      match args with
      | [ arg ] ->
          let at, av = emit_operand h arg in
          if at <> "i8*" then failwith "llvm_emit: print/println expect i8*";
          let c = callee_ll name in
          lines := !lines @ [ Printf.sprintf "  call void @%s(%s %s)" c at av ]
      | _ -> failwith "llvm_emit: print/println expect one argument")
  | Assign (dst, rhs) -> (
      match rhs with
      | Copy o -> emit_copy_dst ctx h lines dst o
      | Binop (b, o1, o2) ->
          let t1, v1 = emit_operand h o1 in
          let t2, v2 = emit_operand h o2 in
          if t1 <> "i32" || t2 <> "i32" then
            failwith "llvm_emit: binop expects i32";
          lines :=
            !lines
            @ [ Printf.sprintf "  %%%s = %s i32 %s, %s" dst (ibin_ll b) v1 v2 ];
          H.replace h dst I32
      | ICmp (c, o1, o2) ->
          let t1, v1 = emit_operand h o1 in
          let t2, v2 = emit_operand h o2 in
          if t1 <> "i32" || t2 <> "i32" then
            failwith "llvm_emit: icmp expects i32";
          lines :=
            !lines
            @ [ Printf.sprintf "  %%%s = icmp %s i32 %s, %s" dst (icmp_ll c) v1 v2 ];
          H.replace h dst I1
      | Call (name, args) -> (
          match name, args with
          | "int_to_str", [ a ] ->
              let ta, va = emit_operand h a in
              if ta <> "i32" then failwith "llvm_emit: int_to_str expects i32";
              let c = callee_ll "int_to_str" in
              lines :=
                !lines
                @ [ Printf.sprintf "  %%%s = call i8* @%s(i32 %s)" dst c va ];
              H.replace h dst String
          | _ -> failwith "llvm_emit: unknown call"))

let emit_term h (lines : string list ref) ~(ret : ty) ~(is_c_main : bool)
    (t : term) : unit =
  let emit_ret op_opt =
    match (is_c_main, ret, op_opt) with
    | true, Unit, None -> lines := !lines @ [ "  ret i32 0" ]
    | true, _, Some o ->
        let ty, v = emit_operand h o in
        if ty = "i32" then lines := !lines @ [ Printf.sprintf "  ret i32 %s" v ]
        else
          failwith "llvm_emit: main must return i32 for C ABI (extend zext)"
    | false, Unit, None -> lines := !lines @ [ "  ret void" ]
    | false, I32, Some o ->
        let _ty, v = emit_operand h o in
        lines := !lines @ [ Printf.sprintf "  ret i32 %s" v ]
    | false, I1, Some o ->
        let _ty, v = emit_operand h o in
        lines := !lines @ [ Printf.sprintf "  ret i1 %s" v ]
    | false, String, Some o ->
        let _ty, v = emit_operand h o in
        lines := !lines @ [ Printf.sprintf "  ret i8* %s" v ]
    | _ -> failwith "llvm_emit: bad return"
  in
  match t with
  | Ret None -> emit_ret None
  | Ret (Some o) -> emit_ret (Some o)
  | Br l -> lines := !lines @ [ Printf.sprintf "  br label %%%s" l ]
  | BrCond (cond, l1, l2) ->
      let ty, v = emit_operand h cond in
      if ty <> "i1" then failwith "llvm_emit: br cond expects i1";
      lines :=
        !lines
        @ [
            Printf.sprintf "  br i1 %s, label %%%s, label %%%s" v l1 l2;
          ]

let init_param_types (f : func_def) : (string, ty) H.t =
  let h = H.create 16 in
  List.iter (fun (p, t) -> H.replace h p t) f.params;
  h

let emit_func ctx (f : func_def) : string =
  let is_c_main = f.name = "main" in
  let ret_s =
    if is_c_main && f.ret = Unit then "i32"
    else llvm_ll_ty f.ret
  in
  let params_s =
    String.concat ", "
      (List.map
         (fun (p, t) ->
           Printf.sprintf "%s %%%s" (llvm_ll_ty t) p)
         f.params)
  in
  let h = init_param_types f in
  let blks = ordered_blocks f.entry f.blocks in
  let body_lines = ref [] in
  List.iter
    (fun blk ->
      body_lines := !body_lines @ [ Printf.sprintf "%s:" blk.label ];
      List.iter (fun i -> emit_instr ctx h body_lines i) blk.instrs;
      emit_term h body_lines ~ret:f.ret ~is_c_main blk.term)
    blks;
  Printf.sprintf "define %s @%s(%s) {\n%s\n}\n" ret_s f.name params_s
    (String.concat "\n" !body_lines)

let emit_prog (p : prog) : string =
  let ctx = ctx_create () in
  let func_text = List.map (emit_func ctx) p.funcs |> String.concat "\n" in
  let globals = String.concat "\n" (List.rev ctx.prelude) in
  let gl_sep = if ctx.prelude = [] then "" else "\n" in
  module_banner ^ runtime_declarations ^ "\n" ^ globals ^ gl_sep ^ func_text
