build:
	dune build main.exe

run:
	dune build main.exe
	dune exec ./main.exe "run" "./../programs/test.txt"

test:
	dune build test/test.exe
	dune exec test/text.exe

repl:
	dune build main.exe
	dune exec ./main.exe "repl"