; Generated by LambdaScript compiler (Min_ir → LLVM IR)
source_filename = "lambdascript"

%ls.clos = type { i8*, i8* }

declare void @ls_print(i8*)
declare void @ls_println(i8*)
declare void @ls_abort()
declare i8* @ls_int_to_str(i32)
declare i8* @ls_str_concat(i8*, i8*)
declare i32 @strcmp(i8*, i8*)
declare i8* @ls_malloc(i64)
declare i8* @ls_mkclos(i8*, i8*)
declare i8* @ls_variant_mk(i32, i8*)
declare i32 @ls_variant_tag(i8*)
declare i8* @ls_variant_payload(i8*)

%ls.tuple.1 = type { i32, i8* }
define i32 @sum(i8* %c) {
entry:
  %_t1 = call i32 @ls_variant_tag(i8* %c)
  %_t2 = icmp eq i32 %_t1, 0
  br i1 %_t2, label %swm_2, label %swn_3
swm_2:
  br label %swm_1
swm_1:
  %_t11 = phi i32 [ 0, %swm_2 ], [ %_t10, %swm_4 ]
  ret i32 %_t11
swn_3:
  %_t3 = call i32 @ls_variant_tag(i8* %c)
  %_t4 = icmp eq i32 %_t3, 1
  %_t5 = call i8* @ls_variant_payload(i8* %c)
  %_t6_uptr = bitcast i8* %_t5 to %ls.tuple.1*
  %_t6 = load %ls.tuple.1, %ls.tuple.1* %_t6_uptr
  %_t7 = extractvalue %ls.tuple.1 %_t6, 0
  %_t8 = extractvalue %ls.tuple.1 %_t6, 1
  br i1 %_t4, label %swm_4, label %swf_5
swm_4:
  %_t9 = call i32 @sum(i8* %_t8)
  %_t10 = add nsw i32 %_t7, %_t9
  br label %swm_1
swf_5:
  call void @ls_abort()
  unreachable
}

define i32 @main() {
entry:
  %_t12 = call i8* @ls_variant_mk(i32 0, i8* null)
  %_t13_pk0 = insertvalue %ls.tuple.1 undef, i32 20, 0
  %_t13 = insertvalue %ls.tuple.1 %_t13_pk0, i8* %_t12, 1
  %_t14 = call i8* @ls_malloc(i64 16)
  %_t14_bptr = bitcast i8* %_t14 to %ls.tuple.1*
  store %ls.tuple.1 %_t13, %ls.tuple.1* %_t14_bptr
  %_t15 = call i8* @ls_variant_mk(i32 1, i8* %_t14)
  %_t16_pk0 = insertvalue %ls.tuple.1 undef, i32 10, 0
  %_t16 = insertvalue %ls.tuple.1 %_t16_pk0, i8* %_t15, 1
  %_t17 = call i8* @ls_malloc(i64 16)
  %_t17_bptr = bitcast i8* %_t17 to %ls.tuple.1*
  store %ls.tuple.1 %_t16, %ls.tuple.1* %_t17_bptr
  %_t18 = call i8* @ls_variant_mk(i32 1, i8* %_t17)
  %_t19 = call i32 @sum(i8* %_t18)
  %_t20 = call i8* @ls_int_to_str(i32 %_t19)
  call void @ls_println(i8* %_t20)
  ret i32 0
}
