; Generated by LambdaScript compiler (Min_ir → LLVM IR)
source_filename = "lambdascript"

%ls.clos = type { i8*, i8* }

declare void @ls_print(i8*)
declare void @ls_println(i8*)
declare void @ls_abort()
declare i8* @ls_int_to_str(i32)
declare i8* @ls_str_concat(i8*, i8*)
declare i32 @strcmp(i8*, i8*)
declare i8* @ls_malloc(i64)
declare i8* @ls_mkclos(i8*, i8*)
declare i8* @ls_variant_mk(i32, i8*)
declare i32 @ls_variant_tag(i8*)
declare i8* @ls_variant_payload(i8*)

%ls.tuple.1 = type { i8*, i8* }
define i32 @sum_tree(i8* %t) {
entry:
  %_t1 = call i32 @ls_variant_tag(i8* %t)
  %_t2 = icmp eq i32 %_t1, 0
  %_t3 = call i8* @ls_variant_payload(i8* %t)
  %_t4_uptr = bitcast i8* %_t3 to i32*
  %_t4 = load i32, i32* %_t4_uptr
  br i1 %_t2, label %swm_2, label %swn_3
swm_2:
  br label %swm_1
swm_1:
  %_t14 = phi i32 [ %_t4, %swm_2 ], [ %_t13, %swm_4 ]
  ret i32 %_t14
swn_3:
  %_t5 = call i32 @ls_variant_tag(i8* %t)
  %_t6 = icmp eq i32 %_t5, 1
  %_t7 = call i8* @ls_variant_payload(i8* %t)
  %_t8_uptr = bitcast i8* %_t7 to %ls.tuple.1*
  %_t8 = load %ls.tuple.1, %ls.tuple.1* %_t8_uptr
  %_t9 = extractvalue %ls.tuple.1 %_t8, 0
  %_t10 = extractvalue %ls.tuple.1 %_t8, 1
  br i1 %_t6, label %swm_4, label %swf_5
swm_4:
  %_t11 = call i32 @sum_tree(i8* %_t9)
  %_t12 = call i32 @sum_tree(i8* %_t10)
  %_t13 = add nsw i32 %_t11, %_t12
  br label %swm_1
swf_5:
  call void @ls_abort()
  unreachable
}

define i32 @main() {
entry:
  %_t15 = call i8* @ls_malloc(i64 4)
  %_t15_bptr = bitcast i8* %_t15 to i32*
  store i32 1, i32* %_t15_bptr
  %_t16 = call i8* @ls_variant_mk(i32 0, i8* %_t15)
  %_t17 = call i8* @ls_malloc(i64 4)
  %_t17_bptr = bitcast i8* %_t17 to i32*
  store i32 2, i32* %_t17_bptr
  %_t18 = call i8* @ls_variant_mk(i32 0, i8* %_t17)
  %_t19 = call i8* @ls_malloc(i64 4)
  %_t19_bptr = bitcast i8* %_t19 to i32*
  store i32 3, i32* %_t19_bptr
  %_t20 = call i8* @ls_variant_mk(i32 0, i8* %_t19)
  %_t21_pk0 = insertvalue %ls.tuple.1 undef, i8* %_t18, 0
  %_t21 = insertvalue %ls.tuple.1 %_t21_pk0, i8* %_t20, 1
  %_t22 = call i8* @ls_malloc(i64 16)
  %_t22_bptr = bitcast i8* %_t22 to %ls.tuple.1*
  store %ls.tuple.1 %_t21, %ls.tuple.1* %_t22_bptr
  %_t23 = call i8* @ls_variant_mk(i32 1, i8* %_t22)
  %_t24_pk0 = insertvalue %ls.tuple.1 undef, i8* %_t16, 0
  %_t24 = insertvalue %ls.tuple.1 %_t24_pk0, i8* %_t23, 1
  %_t25 = call i8* @ls_malloc(i64 16)
  %_t25_bptr = bitcast i8* %_t25 to %ls.tuple.1*
  store %ls.tuple.1 %_t24, %ls.tuple.1* %_t25_bptr
  %_t26 = call i8* @ls_variant_mk(i32 1, i8* %_t25)
  %_t27 = call i32 @sum_tree(i8* %_t26)
  %_t28 = call i8* @ls_int_to_str(i32 %_t27)
  call void @ls_println(i8* %_t28)
  ret i32 0
}
