; Generated by LambdaScript compiler (Min_ir → LLVM IR)
source_filename = "lambdascript"

%ls.clos = type { i8*, i8* }

declare void @ls_print(i8*)
declare void @ls_println(i8*)
declare void @ls_abort()
declare i8* @ls_int_to_str(i32)
declare i8* @ls_str_concat(i8*, i8*)
declare i32 @strcmp(i8*, i8*)
declare i8* @ls_malloc(i64)
declare i8* @ls_mkclos(i8*, i8*)
declare i8* @ls_variant_mk(i32, i8*)
declare i32 @ls_variant_tag(i8*)
declare i8* @ls_variant_payload(i8*)

%ls.env.1 = type { i32 }
%ls.env.2 = type { i32 }
define i8* @get_or__lsm173919979__ls_s0(i8* %_p2, i32 %d) {
entry:
  %_t10 = call i8* @ls_malloc(i64 4)
  %_t11_esb = bitcast i8* %_t10 to %ls.env.1*
  %_t11_esg = getelementptr inbounds %ls.env.1, %ls.env.1* %_t11_esb, i32 0, i32 0
  store i32 %d, i32* %_t11_esg
  %_t12_codep = bitcast i32 (i8*, i8*)* @get_or__lsm173919979__ls_s1 to i8*
  %_t12 = call i8* @ls_mkclos(i8* %_t12_codep, i8* %_t10)
  ret i8* %_t12
}

define i32 @get_or__lsm173919979__ls_s1(i8* %_p1, i8* %o) {
entry:
  %_t8_ebuf = bitcast i8* %_p1 to %ls.env.2*
  %_t8_eg = getelementptr inbounds %ls.env.2, %ls.env.2* %_t8_ebuf, i32 0, i32 0
  %_t8 = load i32, i32* %_t8_eg
  %_t9 = call i32 @get_or__lsm173919979(i32 %_t8, i8* %o)
  ret i32 %_t9
}

define i32 @get_or__lsm173919979(i32 %d, i8* %o) {
entry:
  %_t1 = call i32 @ls_variant_tag(i8* %o)
  %_t2 = icmp eq i32 %_t1, 0
  br i1 %_t2, label %swm_2, label %swn_3
swm_2:
  br label %swm_1
swm_1:
  %_t7 = phi i32 [ %d, %swm_2 ], [ %_t6, %swm_4 ]
  ret i32 %_t7
swn_3:
  %_t3 = call i32 @ls_variant_tag(i8* %o)
  %_t4 = icmp eq i32 %_t3, 1
  %_t5 = call i8* @ls_variant_payload(i8* %o)
  %_t6_uptr = bitcast i8* %_t5 to i32*
  %_t6 = load i32, i32* %_t6_uptr
  br i1 %_t4, label %swm_4, label %swf_5
swm_4:
  br label %swm_1
swf_5:
  call void @ls_abort()
  unreachable
}

define i32 @main() {
entry:
  %_t13 = call i8* @ls_variant_mk(i32 0, i8* null)
  %b__lsm481001565 = bitcast i8* %_t13 to i8*
  %_t14 = call i8* @ls_malloc(i64 4)
  %_t14_bptr = bitcast i8* %_t14 to i32*
  store i32 10, i32* %_t14_bptr
  %_t15 = call i8* @ls_variant_mk(i32 1, i8* %_t14)
  %a = bitcast i8* %_t15 to i8*
  %_t16 = call i8* @ls_variant_mk(i32 0, i8* null)
  %b = bitcast i8* %_t16 to i8*
  %_t17 = call i32 @get_or__lsm173919979(i32 0, i8* %a)
  %_t18 = call i32 @get_or__lsm173919979(i32 100, i8* %b__lsm481001565)
  %_t19 = add nsw i32 %_t17, %_t18
  %_t20 = call i8* @ls_int_to_str(i32 %_t19)
  call void @ls_println(i8* %_t20)
  ret i32 0
}
