; Generated by LambdaScript compiler (Min_ir → LLVM IR)
source_filename = "lambdascript"

%ls.clos = type { i8*, i8* }

declare void @ls_print(i8*)
declare void @ls_println(i8*)
declare void @ls_abort()
declare i8* @ls_int_to_str(i32)
declare i8* @ls_str_concat(i8*, i8*)
declare i32 @strcmp(i8*, i8*)
declare i8* @ls_malloc(i64)
declare i8* @ls_mkclos(i8*, i8*)
declare i8* @ls_variant_mk(i32, i8*)
declare i32 @ls_variant_tag(i8*)
declare i8* @ls_variant_payload(i8*)

%ls.env.1 = type { i8* }
%ls.env.2 = type { i8* }
%ls.tuple.1 = type { i32, i8* }
define i8* @append__lsm928930968__ls_s0(i8* %_p2, i8* %a) {
entry:
  %_t16 = call i8* @ls_malloc(i64 8)
  %_t17_esb = bitcast i8* %_t16 to %ls.env.1*
  %_t17_esg = getelementptr inbounds %ls.env.1, %ls.env.1* %_t17_esb, i32 0, i32 0
  store i8* %a, i8** %_t17_esg
  %_t18_codep = bitcast i8* (i8*, i8*)* @append__lsm928930968__ls_s1 to i8*
  %_t18 = call i8* @ls_mkclos(i8* %_t18_codep, i8* %_t16)
  ret i8* %_t18
}

define i8* @append__lsm928930968__ls_s1(i8* %_p1, i8* %b) {
entry:
  %_t14_ebuf = bitcast i8* %_p1 to %ls.env.2*
  %_t14_eg = getelementptr inbounds %ls.env.2, %ls.env.2* %_t14_ebuf, i32 0, i32 0
  %_t14 = load i8*, i8** %_t14_eg
  %_t15 = call i8* @append__lsm928930968(i8* %_t14, i8* %b)
  ret i8* %_t15
}

define i8* @append__lsm928930968(i8* %a, i8* %b) {
entry:
  %_t1 = call i32 @ls_variant_tag(i8* %a)
  %_t2 = icmp eq i32 %_t1, 0
  br i1 %_t2, label %swm_2, label %swn_3
swm_2:
  br label %swm_1
swm_1:
  %_t13 = phi i8* [ %b, %swm_2 ], [ %_t12, %swm_4 ]
  ret i8* %_t13
swn_3:
  %_t3 = call i32 @ls_variant_tag(i8* %a)
  %_t4 = icmp eq i32 %_t3, 1
  %_t5 = call i8* @ls_variant_payload(i8* %a)
  %_t6_uptr = bitcast i8* %_t5 to %ls.tuple.1*
  %_t6 = load %ls.tuple.1, %ls.tuple.1* %_t6_uptr
  %_t7 = extractvalue %ls.tuple.1 %_t6, 0
  %_t8 = extractvalue %ls.tuple.1 %_t6, 1
  br i1 %_t4, label %swm_4, label %swf_5
swm_4:
  %_t9 = call i8* @append__lsm928930968(i8* %_t8, i8* %b)
  %_t10_pk0 = insertvalue %ls.tuple.1 undef, i32 %_t7, 0
  %_t10 = insertvalue %ls.tuple.1 %_t10_pk0, i8* %_t9, 1
  %_t11 = call i8* @ls_malloc(i64 16)
  %_t11_bptr = bitcast i8* %_t11 to %ls.tuple.1*
  store %ls.tuple.1 %_t10, %ls.tuple.1* %_t11_bptr
  %_t12 = call i8* @ls_variant_mk(i32 1, i8* %_t11)
  br label %swm_1
swf_5:
  call void @ls_abort()
  unreachable
}

define i32 @len__lsm348914431(i8* %lst) {
entry:
  %_t19 = call i32 @ls_variant_tag(i8* %lst)
  %_t20 = icmp eq i32 %_t19, 0
  br i1 %_t20, label %swm_2, label %swn_3
swm_2:
  br label %swm_1
swm_1:
  %_t29 = phi i32 [ 0, %swm_2 ], [ %_t28, %swm_4 ]
  ret i32 %_t29
swn_3:
  %_t21 = call i32 @ls_variant_tag(i8* %lst)
  %_t22 = icmp eq i32 %_t21, 1
  %_t23 = call i8* @ls_variant_payload(i8* %lst)
  %_t24_uptr = bitcast i8* %_t23 to %ls.tuple.1*
  %_t24 = load %ls.tuple.1, %ls.tuple.1* %_t24_uptr
  %_t25 = extractvalue %ls.tuple.1 %_t24, 0
  %_t26 = extractvalue %ls.tuple.1 %_t24, 1
  br i1 %_t22, label %swm_4, label %swf_5
swm_4:
  %_t27 = call i32 @len__lsm348914431(i8* %_t26)
  %_t28 = add nsw i32 1, %_t27
  br label %swm_1
swf_5:
  call void @ls_abort()
  unreachable
}

define i32 @main() {
entry:
  %_t30 = call i8* @ls_variant_mk(i32 0, i8* null)
  %_t31_pk0 = insertvalue %ls.tuple.1 undef, i32 2, 0
  %_t31 = insertvalue %ls.tuple.1 %_t31_pk0, i8* %_t30, 1
  %_t32 = call i8* @ls_malloc(i64 16)
  %_t32_bptr = bitcast i8* %_t32 to %ls.tuple.1*
  store %ls.tuple.1 %_t31, %ls.tuple.1* %_t32_bptr
  %_t33 = call i8* @ls_variant_mk(i32 1, i8* %_t32)
  %_t34_pk0 = insertvalue %ls.tuple.1 undef, i32 1, 0
  %_t34 = insertvalue %ls.tuple.1 %_t34_pk0, i8* %_t33, 1
  %_t35 = call i8* @ls_malloc(i64 16)
  %_t35_bptr = bitcast i8* %_t35 to %ls.tuple.1*
  store %ls.tuple.1 %_t34, %ls.tuple.1* %_t35_bptr
  %_t36 = call i8* @ls_variant_mk(i32 1, i8* %_t35)
  %xs = bitcast i8* %_t36 to i8*
  %_t37 = call i8* @append__lsm928930968(i8* %xs, i8* %xs)
  %_t38 = call i32 @len__lsm348914431(i8* %_t37)
  %_t39 = call i8* @ls_int_to_str(i32 %_t38)
  call void @ls_println(i8* %_t39)
  ret i32 0
}
