; Generated by LambdaScript compiler (Min_ir → LLVM IR)
source_filename = "lambdascript"

%ls.clos = type { i8*, i8* }

declare void @ls_print(i8*)
declare void @ls_println(i8*)
declare void @ls_abort()
declare i8* @ls_int_to_str(i32)
declare i8* @ls_str_concat(i8*, i8*)
declare i32 @strcmp(i8*, i8*)
declare i8* @ls_malloc(i64)
declare i8* @ls_mkclos(i8*, i8*)
declare i8* @ls_variant_mk(i32, i8*)
declare i32 @ls_variant_tag(i8*)
declare i8* @ls_variant_payload(i8*)

%ls.env.1 = type { i32 }
%ls.env.2 = type { i32 }
%ls.tuple.1 = type { i32, i8* }
define i8* @head_def__lsm362376408__ls_s0(i8* %_p2, i32 %d) {
entry:
  %_t12 = call i8* @ls_malloc(i64 4)
  %_t13_esb = bitcast i8* %_t12 to %ls.env.1*
  %_t13_esg = getelementptr inbounds %ls.env.1, %ls.env.1* %_t13_esb, i32 0, i32 0
  store i32 %d, i32* %_t13_esg
  %_t14_codep = bitcast i32 (i8*, i8*)* @head_def__lsm362376408__ls_s1 to i8*
  %_t14 = call i8* @ls_mkclos(i8* %_t14_codep, i8* %_t12)
  ret i8* %_t14
}

define i32 @head_def__lsm362376408__ls_s1(i8* %_p1, i8* %lst) {
entry:
  %_t10_ebuf = bitcast i8* %_p1 to %ls.env.2*
  %_t10_eg = getelementptr inbounds %ls.env.2, %ls.env.2* %_t10_ebuf, i32 0, i32 0
  %_t10 = load i32, i32* %_t10_eg
  %_t11 = call i32 @head_def__lsm362376408(i32 %_t10, i8* %lst)
  ret i32 %_t11
}

define i32 @head_def__lsm362376408(i32 %d, i8* %lst) {
entry:
  %_t1 = call i32 @ls_variant_tag(i8* %lst)
  %_t2 = icmp eq i32 %_t1, 0
  br i1 %_t2, label %swm_2, label %swn_3
swm_2:
  br label %swm_1
swm_1:
  %_t9 = phi i32 [ %d, %swm_2 ], [ %_t7, %swm_4 ]
  ret i32 %_t9
swn_3:
  %_t3 = call i32 @ls_variant_tag(i8* %lst)
  %_t4 = icmp eq i32 %_t3, 1
  %_t5 = call i8* @ls_variant_payload(i8* %lst)
  %_t6_uptr = bitcast i8* %_t5 to %ls.tuple.1*
  %_t6 = load %ls.tuple.1, %ls.tuple.1* %_t6_uptr
  %_t7 = extractvalue %ls.tuple.1 %_t6, 0
  %_t8 = extractvalue %ls.tuple.1 %_t6, 1
  br i1 %_t4, label %swm_4, label %swf_5
swm_4:
  br label %swm_1
swf_5:
  call void @ls_abort()
  unreachable
}

define i32 @main() {
entry:
  %_t15 = call i8* @ls_variant_mk(i32 0, i8* null)
  %_t16_pk0 = insertvalue %ls.tuple.1 undef, i32 5, 0
  %_t16 = insertvalue %ls.tuple.1 %_t16_pk0, i8* %_t15, 1
  %_t17 = call i8* @ls_malloc(i64 16)
  %_t17_bptr = bitcast i8* %_t17 to %ls.tuple.1*
  store %ls.tuple.1 %_t16, %ls.tuple.1* %_t17_bptr
  %_t18 = call i8* @ls_variant_mk(i32 1, i8* %_t17)
  %_t19 = call i32 @head_def__lsm362376408(i32 0, i8* %_t18)
  %_t20 = call i8* @ls_int_to_str(i32 %_t19)
  call void @ls_println(i8* %_t20)
  ret i32 0
}
