; Generated by LambdaScript compiler (Min_ir → LLVM IR)
source_filename = "lambdascript"

declare void @ls_print(i8*)
declare void @ls_println(i8*)
declare i8* @ls_int_to_str(i32)

define i32 @main() {
entry:
  %_t1 = icmp sle i32 1, 2
  %_t2 = icmp sge i32 3, 3
  %_t3 = icmp sge i32 2, 5
  %_t4 = or i1 %_t3, true
  %_t5 = and i1 %_t2, %_t4
  %_t6 = and i1 %_t1, %_t5
  br i1 %_t6, label %then_1, label %else_2
then_1:
  br label %merge_3
merge_3:
  %_t7 = phi i32 [ 99, %then_1 ], [ 0, %else_2 ]
  %_t8 = call i8* @ls_int_to_str(i32 %_t7)
  call void @ls_println(i8* %_t8)
  ret i32 0
else_2:
  br label %merge_3
}
