; Generated by LambdaScript compiler (Min_ir → LLVM IR)
source_filename = "lambdascript"

declare void @ls_print(i8*)
declare void @ls_println(i8*)
declare i8* @ls_int_to_str(i32)

define i32 @apply(i32 (i32)* %f, i32 %x) {
entry:
  %_t1 = call i32 %f(i32 %x)
  ret i32 %_t1
}

define i32 @inc(i32 %y) {
entry:
  %_t2 = add nsw i32 %y, 1
  ret i32 %_t2
}

define i32 @main() {
entry:
  %_t3 = call i32 @apply(i32 (i32)* @inc, i32 41)
  %_t4 = call i8* @ls_int_to_str(i32 %_t3)
  call void @ls_println(i8* %_t4)
  ret i32 0
}
