; Generated by LambdaScript compiler (Min_ir → LLVM IR)
source_filename = "lambdascript"

declare void @ls_print(i8*)
declare void @ls_println(i8*)
declare i8* @ls_int_to_str(i32)

define i32 @main() {
entry:
  br i1 true, label %then_1, label %else_2
then_1:
  br label %merge_3
merge_3:
  %_t1 = phi i32 [ 42, %then_1 ], [ 0, %else_2 ]
  %_t2 = call i8* @ls_int_to_str(i32 %_t1)
  call void @ls_println(i8* %_t2)
  ret i32 0
else_2:
  br label %merge_3
}
