; Generated by LambdaScript compiler (Min_ir → LLVM IR)
source_filename = "lambdascript"

declare void @ls_print(i8*)
declare void @ls_println(i8*)
declare i8* @ls_int_to_str(i32)

@.str.0 = private unnamed_addr constant [4 x i8] c"yes\00"
@.str.1 = private unnamed_addr constant [3 x i8] c"no\00"
define i32 @main() {
entry:
  br i1 false, label %then_1, label %else_2
then_1:
  %_t1 = getelementptr inbounds [4 x i8], [4 x i8]* @.str.0, i64 0, i64 0
  call void @ls_println(i8* %_t1)
  br label %merge_3
merge_3:
  ret i32 0
else_2:
  %_t2 = getelementptr inbounds [3 x i8], [3 x i8]* @.str.1, i64 0, i64 0
  call void @ls_println(i8* %_t2)
  br label %merge_3
}
