; Generated by LambdaScript compiler (Min_ir → LLVM IR)
source_filename = "lambdascript"

declare void @ls_print(i8*)
declare void @ls_println(i8*)
declare i8* @ls_int_to_str(i32)

@.str.0 = private unnamed_addr constant [4 x i8] c"yes\00"
@.str.1 = private unnamed_addr constant [5 x i8] c"yes1\00"
@.str.2 = private unnamed_addr constant [3 x i8] c"no\00"
define i32 @main() {
entry:
  br i1 false, label %then_1, label %else_2
then_1:
  %_t1 = getelementptr inbounds [4 x i8], [4 x i8]* @.str.0, i64 0, i64 0
  call void @ls_println(i8* %_t1)
  br label %merge_3
merge_3:
  %a = add nsw i32 1, 0
  %b = add nsw i32 2, 0
  %c = add nsw i32 3, 0
  %d = add nsw i32 4, 0
  %_t4 = add nsw i32 %a, %b
  %_t5 = add nsw i32 %_t4, %c
  %_t6 = add nsw i32 %_t5, %d
  %x = add nsw i32 %_t6, 0
  %_t7 = call i8* @ls_int_to_str(i32 %x)
  call void @ls_println(i8* %_t7)
  ret i32 0
else_2:
  br i1 true, label %then_4, label %else_5
then_4:
  %_t2 = getelementptr inbounds [5 x i8], [5 x i8]* @.str.1, i64 0, i64 0
  call void @ls_println(i8* %_t2)
  br label %merge_6
merge_6:
  br label %merge_3
else_5:
  %_t3 = getelementptr inbounds [3 x i8], [3 x i8]* @.str.2, i64 0, i64 0
  call void @ls_println(i8* %_t3)
  br label %merge_6
}
