; Generated by LambdaScript compiler (Min_ir → LLVM IR)
source_filename = "lambdascript"

%ls.clos = type { i8*, i8* }

declare void @ls_print(i8*)
declare void @ls_println(i8*)
declare void @ls_abort()
declare i8* @ls_int_to_str(i32)
declare i8* @ls_str_concat(i8*, i8*)
declare i32 @strcmp(i8*, i8*)
declare i8* @ls_malloc(i64)
declare i8* @ls_mkclos(i8*, i8*)

%ls.lcell.1 = type { i32, i8* }
define i32 @sum(i8* %lst) {
entry:
  %_t1 = icmp eq i8* %lst, null
  br i1 %_t1, label %swm_2, label %swn_3
swm_2:
  br label %swm_1
swm_1:
  %_t7 = phi i32 [ 0, %swm_2 ], [ %_t6, %swm_4 ]
  ret i32 %_t7
swn_3:
  %_t2 = icmp ne i8* %lst, null
  %_t3_lcp = bitcast i8* %lst to %ls.lcell.1*
  %_t3_gh = getelementptr inbounds %ls.lcell.1, %ls.lcell.1* %_t3_lcp, i32 0, i32 0
  %_t3 = load i32, i32* %_t3_gh
  %_t4_tcp = bitcast i8* %lst to %ls.lcell.1*
  %_t4_tg = getelementptr inbounds %ls.lcell.1, %ls.lcell.1* %_t4_tcp, i32 0, i32 1
  %_t4 = load i8*, i8** %_t4_tg
  br i1 %_t2, label %swm_4, label %swf_5
swm_4:
  %_t5 = call i32 @sum(i8* %_t4)
  %_t6 = add nsw i32 %_t3, %_t5
  br label %swm_1
swf_5:
  call void @ls_abort()
  unreachable
}

define i32 @main() {
entry:
  %_t8 = bitcast i8* null to i8*
  br label %lrh_1
lrh_1:
  %_t9 = phi i32 [ 4, %entry ], [ %_t11, %lrb_2 ]
  %_t10 = phi i8* [ %_t8, %entry ], [ %_t12, %lrb_2 ]
  %_t13 = icmp sge i32 %_t9, 0
  br i1 %_t13, label %lrb_2, label %lre_3
lrb_2:
  %_t12_raw = call i8* @ls_malloc(i64 16)
  %_t12_cp = bitcast i8* %_t12_raw to %ls.lcell.1*
  %_t12_gh = getelementptr inbounds %ls.lcell.1, %ls.lcell.1* %_t12_cp, i32 0, i32 0
  store i32 %_t9, i32* %_t12_gh
  %_t12_gt = getelementptr inbounds %ls.lcell.1, %ls.lcell.1* %_t12_cp, i32 0, i32 1
  store i8* %_t10, i8** %_t12_gt
  %_t12 = bitcast %ls.lcell.1* %_t12_cp to i8*
  %_t11 = sub nsw i32 %_t9, 1
  br label %lrh_1
lre_3:
  %_t14 = call i32 @sum(i8* %_t10)
  %_t15 = call i8* @ls_int_to_str(i32 %_t14)
  call void @ls_println(i8* %_t15)
  %_t16 = bitcast i8* null to i8*
  %_t17_raw = call i8* @ls_malloc(i64 16)
  %_t17_cp = bitcast i8* %_t17_raw to %ls.lcell.1*
  %_t17_gh = getelementptr inbounds %ls.lcell.1, %ls.lcell.1* %_t17_cp, i32 0, i32 0
  store i32 4, i32* %_t17_gh
  %_t17_gt = getelementptr inbounds %ls.lcell.1, %ls.lcell.1* %_t17_cp, i32 0, i32 1
  store i8* %_t16, i8** %_t17_gt
  %_t17 = bitcast %ls.lcell.1* %_t17_cp to i8*
  %_t18_raw = call i8* @ls_malloc(i64 16)
  %_t18_cp = bitcast i8* %_t18_raw to %ls.lcell.1*
  %_t18_gh = getelementptr inbounds %ls.lcell.1, %ls.lcell.1* %_t18_cp, i32 0, i32 0
  store i32 3, i32* %_t18_gh
  %_t18_gt = getelementptr inbounds %ls.lcell.1, %ls.lcell.1* %_t18_cp, i32 0, i32 1
  store i8* %_t17, i8** %_t18_gt
  %_t18 = bitcast %ls.lcell.1* %_t18_cp to i8*
  %_t19_raw = call i8* @ls_malloc(i64 16)
  %_t19_cp = bitcast i8* %_t19_raw to %ls.lcell.1*
  %_t19_gh = getelementptr inbounds %ls.lcell.1, %ls.lcell.1* %_t19_cp, i32 0, i32 0
  store i32 2, i32* %_t19_gh
  %_t19_gt = getelementptr inbounds %ls.lcell.1, %ls.lcell.1* %_t19_cp, i32 0, i32 1
  store i8* %_t18, i8** %_t19_gt
  %_t19 = bitcast %ls.lcell.1* %_t19_cp to i8*
  %_t20_raw = call i8* @ls_malloc(i64 16)
  %_t20_cp = bitcast i8* %_t20_raw to %ls.lcell.1*
  %_t20_gh = getelementptr inbounds %ls.lcell.1, %ls.lcell.1* %_t20_cp, i32 0, i32 0
  store i32 1, i32* %_t20_gh
  %_t20_gt = getelementptr inbounds %ls.lcell.1, %ls.lcell.1* %_t20_cp, i32 0, i32 1
  store i8* %_t19, i8** %_t20_gt
  %_t20 = bitcast %ls.lcell.1* %_t20_cp to i8*
  %_t21_raw = call i8* @ls_malloc(i64 16)
  %_t21_cp = bitcast i8* %_t21_raw to %ls.lcell.1*
  %_t21_gh = getelementptr inbounds %ls.lcell.1, %ls.lcell.1* %_t21_cp, i32 0, i32 0
  store i32 0, i32* %_t21_gh
  %_t21_gt = getelementptr inbounds %ls.lcell.1, %ls.lcell.1* %_t21_cp, i32 0, i32 1
  store i8* %_t20, i8** %_t21_gt
  %_t21 = bitcast %ls.lcell.1* %_t21_cp to i8*
  %_t22 = call i32 @sum(i8* %_t21)
  %_t23 = call i8* @ls_int_to_str(i32 %_t22)
  call void @ls_println(i8* %_t23)
  ret i32 0
}
