; Generated by LambdaScript compiler (Min_ir → LLVM IR)
source_filename = "lambdascript"

declare void @ls_print(i8*)
declare void @ls_println(i8*)
declare i8* @ls_int_to_str(i32)

define i32 @main() {
entry:
  %_t1 = add nsw i32 1, 2
  %x = add nsw i32 %_t1, 0
  %_t2 = call i8* @ls_int_to_str(i32 %x)
  call void @ls_println(i8* %_t2)
  ret i32 0
}
