; Generated by LambdaScript compiler (Min_ir → LLVM IR)
source_filename = "lambdascript"

declare void @ls_print(i8*)
declare void @ls_println(i8*)
declare i8* @ls_int_to_str(i32)

define i1 @even(i32 %n) {
entry:
  %_t1 = icmp eq i32 %n, 0
  br i1 %_t1, label %then_1, label %else_2
then_1:
  br label %merge_3
merge_3:
  %_t4 = phi i1 [ true, %then_1 ], [ %_t3, %else_2 ]
  ret i1 %_t4
else_2:
  %_t2 = sub nsw i32 %n, 1
  %_t3 = call i1 @odd(i32 %_t2)
  br label %merge_3
}

define i1 @odd(i32 %n) {
entry:
  %_t5 = icmp eq i32 %n, 0
  br i1 %_t5, label %then_1, label %else_2
then_1:
  br label %merge_3
merge_3:
  %_t8 = phi i1 [ false, %then_1 ], [ %_t7, %else_2 ]
  ret i1 %_t8
else_2:
  %_t6 = sub nsw i32 %n, 1
  %_t7 = call i1 @even(i32 %_t6)
  br label %merge_3
}

define i32 @main() {
entry:
  %_t9 = call i1 @odd(i32 7)
  br i1 %_t9, label %then_1, label %else_2
then_1:
  br label %merge_3
merge_3:
  %_t10 = phi i32 [ 1, %then_1 ], [ 0, %else_2 ]
  %_t11 = call i8* @ls_int_to_str(i32 %_t10)
  call void @ls_println(i8* %_t11)
  ret i32 0
else_2:
  br label %merge_3
}
