; Generated by LambdaScript compiler (Min_ir → LLVM IR)
source_filename = "lambdascript"

%ls.clos = type { i8*, i8* }

declare void @ls_print(i8*)
declare void @ls_println(i8*)
declare i8* @ls_int_to_str(i32)
declare i8* @ls_malloc(i64)
declare i8* @ls_mkclos(i8*, i8*)

define i32 @id__lsm966650245(i32 %x) {
entry:
  ret i32 %x
}

define i32 @use__lsm76640768(i32 (i32)* %g) {
entry:
  %_t1 = call i32 %g(i32 1)
  ret i32 %_t1
}

define i32 @main() {
entry:
  %_t2 = call i32 @use__lsm76640768(i32 (i32)* @id__lsm966650245)
  %_t3 = call i8* @ls_int_to_str(i32 %_t2)
  call void @ls_println(i8* %_t3)
  ret i32 0
}
