; Generated by LambdaScript compiler (Min_ir → LLVM IR)
source_filename = "lambdascript"

%ls.clos = type { i8*, i8* }

declare void @ls_print(i8*)
declare void @ls_println(i8*)
declare i8* @ls_int_to_str(i32)
declare i8* @ls_malloc(i64)
declare i8* @ls_mkclos(i8*, i8*)

%ls.env.1 = type { i32 (i32)* }
%ls.env.2 = type { i32 (i32)* }
define i8* @apply__lsm509404921__ls_s0(i8* %_p2, i32 (i32)* %f) {
entry:
  %_t4 = call i8* @ls_malloc(i64 8)
  %_t5_esb = bitcast i8* %_t4 to %ls.env.1*
  %_t5_esg = getelementptr inbounds %ls.env.1, %ls.env.1* %_t5_esb, i32 0, i32 0
  store i32 (i32)* %f, i32 (i32)** %_t5_esg
  %_t6_codep = bitcast i32 (i8*, i32)* @apply__lsm509404921__ls_s1 to i8*
  %_t6 = call i8* @ls_mkclos(i8* %_t6_codep, i8* %_t4)
  ret i8* %_t6
}

define i32 @apply__lsm509404921__ls_s1(i8* %_p1, i32 %x) {
entry:
  %_t2_ebuf = bitcast i8* %_p1 to %ls.env.2*
  %_t2_eg = getelementptr inbounds %ls.env.2, %ls.env.2* %_t2_ebuf, i32 0, i32 0
  %_t2 = load i32 (i32)*, i32 (i32)** %_t2_eg
  %_t3 = call i32 @apply__lsm509404921(i32 (i32)* %_t2, i32 %x)
  ret i32 %_t3
}

define i32 @apply__lsm509404921(i32 (i32)* %f, i32 %x) {
entry:
  %_t1 = call i32 %f(i32 %x)
  ret i32 %_t1
}

define i32 @square(i32 %n) {
entry:
  %_t7 = mul nsw i32 %n, %n
  ret i32 %_t7
}

define i32 @h(i32 %__ls_eta_1) {
entry:
  %_t8 = call i32 @apply__lsm509404921(i32 (i32)* @square, i32 %__ls_eta_1)
  ret i32 %_t8
}

define i32 @main() {
entry:
  %_t9 = call i32 @h(i32 5)
  %_t10 = call i8* @ls_int_to_str(i32 %_t9)
  call void @ls_println(i8* %_t10)
  ret i32 0
}
