; Generated by LambdaScript compiler (Min_ir → LLVM IR)
source_filename = "lambdascript"

%ls.clos = type { i8*, i8* }

declare void @ls_print(i8*)
declare void @ls_println(i8*)
declare void @ls_abort()
declare i8* @ls_int_to_str(i32)
declare i8* @ls_str_concat(i8*, i8*)
declare i32 @strcmp(i8*, i8*)
declare i8* @ls_malloc(i64)
declare i8* @ls_mkclos(i8*, i8*)

%ls.env.1 = type { i32 }
%ls.env.2 = type { i32 }
%ls.env.3 = type { i8* }
%ls.env.4 = type { i8* }
%ls.env.5 = type { i8* }
%ls.env.6 = type { i8* }
%ls.env.7 = type { i8* }
%ls.env.8 = type { i8* }
define i8* @id__lsm76640768__ls_s0(i8* %_p2, i32 %x) {
entry:
  %_t3 = call i8* @ls_malloc(i64 4)
  %_t4_esb = bitcast i8* %_t3 to %ls.env.1*
  %_t4_esg = getelementptr inbounds %ls.env.1, %ls.env.1* %_t4_esb, i32 0, i32 0
  store i32 %x, i32* %_t4_esg
  %_t5_codep = bitcast i32 (i8*, i32)* @id__lsm76640768__ls_s1 to i8*
  %_t5 = call i8* @ls_mkclos(i8* %_t5_codep, i8* %_t3)
  ret i8* %_t5
}

define i32 @id__lsm76640768__ls_s1(i8* %_p1, i32 %y) {
entry:
  %_t1_ebuf = bitcast i8* %_p1 to %ls.env.2*
  %_t1_eg = getelementptr inbounds %ls.env.2, %ls.env.2* %_t1_ebuf, i32 0, i32 0
  %_t1 = load i32, i32* %_t1_eg
  %_t2 = call i32 @id__lsm76640768(i32 %_t1, i32 %y)
  ret i32 %_t2
}

define i32 @id__lsm76640768(i32 %x, i32 %y) {
entry:
  ret i32 %x
}

define i8* @id__lsm265992483__ls_s0(i8* %_p4, i8* %x) {
entry:
  %_t8 = call i8* @ls_malloc(i64 8)
  %_t9_esb = bitcast i8* %_t8 to %ls.env.3*
  %_t9_esg = getelementptr inbounds %ls.env.3, %ls.env.3* %_t9_esb, i32 0, i32 0
  store i8* %x, i8** %_t9_esg
  %_t10_codep = bitcast i8* (i8*, i1)* @id__lsm265992483__ls_s1 to i8*
  %_t10 = call i8* @ls_mkclos(i8* %_t10_codep, i8* %_t8)
  ret i8* %_t10
}

define i8* @id__lsm265992483__ls_s1(i8* %_p3, i1 %y) {
entry:
  %_t6_ebuf = bitcast i8* %_p3 to %ls.env.4*
  %_t6_eg = getelementptr inbounds %ls.env.4, %ls.env.4* %_t6_ebuf, i32 0, i32 0
  %_t6 = load i8*, i8** %_t6_eg
  %_t7 = call i8* @id__lsm265992483(i8* %_t6, i1 %y)
  ret i8* %_t7
}

define i8* @id__lsm265992483(i8* %x, i1 %y) {
entry:
  ret i8* %x
}

define i8* @id__lsm999492867__ls_s0(i8* %_p6, i8* %x) {
entry:
  %_t13 = call i8* @ls_malloc(i64 8)
  %_t14_esb = bitcast i8* %_t13 to %ls.env.5*
  %_t14_esg = getelementptr inbounds %ls.env.5, %ls.env.5* %_t14_esb, i32 0, i32 0
  store i8* %x, i8** %_t14_esg
  %_t15_codep = bitcast i8* (i8*, i1)* @id__lsm999492867__ls_s1 to i8*
  %_t15 = call i8* @ls_mkclos(i8* %_t15_codep, i8* %_t13)
  ret i8* %_t15
}

define i8* @id__lsm999492867__ls_s1(i8* %_p5, i1 %y) {
entry:
  %_t11_ebuf = bitcast i8* %_p5 to %ls.env.6*
  %_t11_eg = getelementptr inbounds %ls.env.6, %ls.env.6* %_t11_ebuf, i32 0, i32 0
  %_t11 = load i8*, i8** %_t11_eg
  %_t12 = call i8* @id__lsm999492867(i8* %_t11, i1 %y)
  ret i8* %_t12
}

define i8* @id__lsm999492867(i8* %x, i1 %y) {
entry:
  ret i8* %x
}

define i8* @id__lsm16355563__ls_s0(i8* %_p8, i8* %x) {
entry:
  %_t18 = call i8* @ls_malloc(i64 8)
  %_t19_esb = bitcast i8* %_t18 to %ls.env.7*
  %_t19_esg = getelementptr inbounds %ls.env.7, %ls.env.7* %_t19_esb, i32 0, i32 0
  store i8* %x, i8** %_t19_esg
  %_t20_codep = bitcast i8* (i8*, i32)* @id__lsm16355563__ls_s1 to i8*
  %_t20 = call i8* @ls_mkclos(i8* %_t20_codep, i8* %_t18)
  ret i8* %_t20
}

define i8* @id__lsm16355563__ls_s1(i8* %_p7, i32 %y) {
entry:
  %_t16_ebuf = bitcast i8* %_p7 to %ls.env.8*
  %_t16_eg = getelementptr inbounds %ls.env.8, %ls.env.8* %_t16_ebuf, i32 0, i32 0
  %_t16 = load i8*, i8** %_t16_eg
  %_t17 = call i8* @id__lsm16355563(i8* %_t16, i32 %y)
  ret i8* %_t17
}

define i8* @id__lsm16355563(i8* %x, i32 %y) {
entry:
  ret i8* %x
}

define i32 @lam__lsn1(i32 %x) {
entry:
  ret i32 %x
}

define i32 @main() {
entry:
  %_t21_codep = bitcast i8* (i8*, i32)* @id__lsm76640768__ls_s0 to i8*
  %_t21 = call i8* @ls_mkclos(i8* %_t21_codep, i8* null)
  %_t22 = call i8* @id__lsm16355563(i8* %_t21, i32 10)
  %_t23 = call i8* @id__lsm265992483(i8* %_t22, i1 true)
  %_t24_cp = bitcast i8* %_t23 to %ls.clos*
  %_t24_gcd = getelementptr inbounds %ls.clos, %ls.clos* %_t24_cp, i32 0, i32 0
  %_t24_vcd = load i8*, i8** %_t24_gcd
  %_t24_gen = getelementptr inbounds %ls.clos, %ls.clos* %_t24_cp, i32 0, i32 1
  %_t24_ven = load i8*, i8** %_t24_gen
  %_t24_fn = bitcast i8* %_t24_vcd to i8* (i8*, i32)*
  %_t24 = call i8* %_t24_fn(i8* %_t24_ven, i32 1)
  %_t25_cp = bitcast i8* %_t24 to %ls.clos*
  %_t25_gcd = getelementptr inbounds %ls.clos, %ls.clos* %_t25_cp, i32 0, i32 0
  %_t25_vcd = load i8*, i8** %_t25_gcd
  %_t25_gen = getelementptr inbounds %ls.clos, %ls.clos* %_t25_cp, i32 0, i32 1
  %_t25_ven = load i8*, i8** %_t25_gen
  %_t25_fn = bitcast i8* %_t25_vcd to i32 (i8*, i32 (i32)*)*
  %_t25 = call i32 %_t25_fn(i8* %_t25_ven, i32 (i32)* @lam__lsn1)
  %a = add nsw i32 %_t25, 0
  %_t26 = call i8* @ls_int_to_str(i32 %a)
  call void @ls_println(i8* %_t26)
  ret i32 0
}
