; Generated by LambdaScript compiler (Min_ir → LLVM IR)
source_filename = "lambdascript"

%ls.clos = type { i8*, i8* }

declare void @ls_print(i8*)
declare void @ls_println(i8*)
declare void @ls_abort()
declare i8* @ls_int_to_str(i32)
declare i8* @ls_str_concat(i8*, i8*)
declare i32 @strcmp(i8*, i8*)
declare i8* @ls_malloc(i64)
declare i8* @ls_mkclos(i8*, i8*)

%ls.env.1 = type { i32 }
%ls.env.2 = type { i32 }
%ls.env.3 = type { i32 }
%ls.env.4 = type { i32 }
define i8* @id__lsm76640768__ls_s0(i8* %_p2, i32 %x) {
entry:
  %_t3 = call i8* @ls_malloc(i64 4)
  %_t4_esb = bitcast i8* %_t3 to %ls.env.1*
  %_t4_esg = getelementptr inbounds %ls.env.1, %ls.env.1* %_t4_esb, i32 0, i32 0
  store i32 %x, i32* %_t4_esg
  %_t5_codep = bitcast i32 (i8*, i32)* @id__lsm76640768__ls_s1 to i8*
  %_t5 = call i8* @ls_mkclos(i8* %_t5_codep, i8* %_t3)
  ret i8* %_t5
}

define i32 @id__lsm76640768__ls_s1(i8* %_p1, i32 %y) {
entry:
  %_t1_ebuf = bitcast i8* %_p1 to %ls.env.2*
  %_t1_eg = getelementptr inbounds %ls.env.2, %ls.env.2* %_t1_ebuf, i32 0, i32 0
  %_t1 = load i32, i32* %_t1_eg
  %_t2 = call i32 @id__lsm76640768(i32 %_t1, i32 %y)
  ret i32 %_t2
}

define i32 @id__lsm76640768(i32 %x, i32 %y) {
entry:
  ret i32 %x
}

define i8* @id__lsm509404921__ls_s0(i8* %_p4, i32 %x) {
entry:
  %_t8 = call i8* @ls_malloc(i64 4)
  %_t9_esb = bitcast i8* %_t8 to %ls.env.3*
  %_t9_esg = getelementptr inbounds %ls.env.3, %ls.env.3* %_t9_esb, i32 0, i32 0
  store i32 %x, i32* %_t9_esg
  %_t10_codep = bitcast i32 (i8*, i32 (i32)*)* @id__lsm509404921__ls_s1 to i8*
  %_t10 = call i8* @ls_mkclos(i8* %_t10_codep, i8* %_t8)
  ret i8* %_t10
}

define i32 @id__lsm509404921__ls_s1(i8* %_p3, i32 (i32)* %y) {
entry:
  %_t6_ebuf = bitcast i8* %_p3 to %ls.env.4*
  %_t6_eg = getelementptr inbounds %ls.env.4, %ls.env.4* %_t6_ebuf, i32 0, i32 0
  %_t6 = load i32, i32* %_t6_eg
  %_t7 = call i32 @id__lsm509404921(i32 %_t6, i32 (i32)* %y)
  ret i32 %_t7
}

define i32 @id__lsm509404921(i32 %x, i32 (i32)* %y) {
entry:
  ret i32 %x
}

define i32 @lam__lsn1(i32 %x) {
entry:
  ret i32 %x
}

define i32 @main() {
entry:
  %_t11 = call i32 @id__lsm509404921(i32 1, i32 (i32)* @lam__lsn1)
  %a = add nsw i32 %_t11, 0
  %_t12 = call i8* @ls_int_to_str(i32 %a)
  call void @ls_println(i8* %_t12)
  ret i32 0
}
