; Generated by LambdaScript compiler (Min_ir → LLVM IR)
source_filename = "lambdascript"

%ls.clos = type { i8*, i8* }

declare void @ls_print(i8*)
declare void @ls_println(i8*)
declare void @ls_abort()
declare i8* @ls_int_to_str(i32)
declare i8* @ls_str_concat(i8*, i8*)
declare i32 @strcmp(i8*, i8*)
declare i8* @ls_malloc(i64)
declare i8* @ls_mkclos(i8*, i8*)
declare i8* @ls_variant_mk(i32, i8*)
declare i32 @ls_variant_tag(i8*)
declare i8* @ls_variant_payload(i8*)

define i32 @main() {
entry:
  %_t1 = call i8* @ls_malloc(i64 4)
  %_t1_bptr = bitcast i8* %_t1 to i32*
  store i32 7, i32* %_t1_bptr
  %_t2 = call i8* @ls_variant_mk(i32 1, i8* %_t1)
  %_t3 = call i8* @ls_malloc(i64 8)
  %_t3_bptr = bitcast i8* %_t3 to i8**
  store i8* %_t2, i8** %_t3_bptr
  %_t4 = call i8* @ls_variant_mk(i32 1, i8* %_t3)
  %x = bitcast i8* %_t4 to i8*
  %_t5 = call i8* @ls_int_to_str(i32 1)
  call void @ls_println(i8* %_t5)
  ret i32 0
}
