; Generated by LambdaScript compiler (Min_ir → LLVM IR)
source_filename = "lambdascript"

%ls.clos = type { i8*, i8* }

declare void @ls_print(i8*)
declare void @ls_println(i8*)
declare void @ls_abort()
declare i8* @ls_int_to_str(i32)
declare i8* @ls_str_concat(i8*, i8*)
declare i32 @strcmp(i8*, i8*)
declare i8* @ls_malloc(i64)
declare i8* @ls_mkclos(i8*, i8*)
declare i8* @ls_variant_mk(i32, i8*)
declare i32 @ls_variant_tag(i8*)
declare i8* @ls_variant_payload(i8*)

define i32 @even_val(i8* %e) {
entry:
  %_t1 = call i32 @ls_variant_tag(i8* %e)
  %_t2 = icmp eq i32 %_t1, 0
  br i1 %_t2, label %swm_2, label %swn_3
swm_2:
  br label %swm_1
swm_1:
  %_t9 = phi i32 [ 0, %swm_2 ], [ %_t8, %swm_4 ]
  ret i32 %_t9
swn_3:
  %_t3 = call i32 @ls_variant_tag(i8* %e)
  %_t4 = icmp eq i32 %_t3, 1
  %_t5 = call i8* @ls_variant_payload(i8* %e)
  %_t6_uptr = bitcast i8* %_t5 to i8**
  %_t6 = load i8*, i8** %_t6_uptr
  br i1 %_t4, label %swm_4, label %swf_5
swm_4:
  %_t7 = call i32 @odd_val(i8* %_t6)
  %_t8 = add nsw i32 1, %_t7
  br label %swm_1
swf_5:
  call void @ls_abort()
  unreachable
}

define i32 @odd_val(i8* %o) {
entry:
  %_t10 = call i32 @ls_variant_tag(i8* %o)
  %_t11 = icmp eq i32 %_t10, 0
  %_t12 = call i8* @ls_variant_payload(i8* %o)
  %_t13_uptr = bitcast i8* %_t12 to i8**
  %_t13 = load i8*, i8** %_t13_uptr
  br i1 %_t11, label %sws_2, label %swf_3
sws_2:
  %_t14 = call i32 @even_val(i8* %_t13)
  %_t15 = add nsw i32 1, %_t14
  br label %swm_1
swm_1:
  %_t16 = phi i32 [ %_t15, %sws_2 ]
  ret i32 %_t16
swf_3:
  call void @ls_abort()
  unreachable
}

define i32 @main() {
entry:
  %_t17 = call i8* @ls_variant_mk(i32 0, i8* null)
  %_t18 = call i8* @ls_malloc(i64 8)
  %_t18_bptr = bitcast i8* %_t18 to i8**
  store i8* %_t17, i8** %_t18_bptr
  %_t19 = call i8* @ls_variant_mk(i32 0, i8* %_t18)
  %_t20 = call i8* @ls_malloc(i64 8)
  %_t20_bptr = bitcast i8* %_t20 to i8**
  store i8* %_t19, i8** %_t20_bptr
  %_t21 = call i8* @ls_variant_mk(i32 1, i8* %_t20)
  %two = bitcast i8* %_t21 to i8*
  %_t22 = call i32 @even_val(i8* %two)
  %_t23 = call i8* @ls_int_to_str(i32 %_t22)
  call void @ls_println(i8* %_t23)
  ret i32 0
}
