; Generated by LambdaScript compiler (Min_ir → LLVM IR)
source_filename = "lambdascript"

declare void @ls_print(i8*)
declare void @ls_println(i8*)
declare i8* @ls_int_to_str(i32)

define i32 @fact_helper__lsn1(i32 %n, i32 %acc) {
entry:
  %_t1 = icmp eq i32 %n, 0
  br i1 %_t1, label %then_1, label %else_2
then_1:
  br label %merge_3
merge_3:
  %_t5 = phi i32 [ %acc, %then_1 ], [ %_t4, %else_2 ]
  ret i32 %_t5
else_2:
  %_t2 = sub nsw i32 %n, 1
  %_t3 = mul nsw i32 %n, %acc
  %_t4 = call i32 @fact_helper__lsn1(i32 %_t2, i32 %_t3)
  br label %merge_3
}

define i32 @fact(i32 %n) {
entry:
  %_t6 = call i32 @fact_helper__lsn1(i32 %n, i32 1)
  ret i32 %_t6
}

define i32 @main() {
entry:
  %_t7 = call i32 @fact(i32 5)
  %_t8 = call i8* @ls_int_to_str(i32 %_t7)
  call void @ls_println(i8* %_t8)
  ret i32 0
}
