; Generated by LambdaScript compiler (Min_ir → LLVM IR)
source_filename = "lambdascript"

%ls.clos = type { i8*, i8* }

declare void @ls_print(i8*)
declare void @ls_println(i8*)
declare void @ls_abort()
declare i8* @ls_int_to_str(i32)
declare i8* @ls_str_concat(i8*, i8*)
declare i32 @strcmp(i8*, i8*)
declare i8* @ls_malloc(i64)
declare i8* @ls_mkclos(i8*, i8*)
declare i8* @ls_variant_mk(i32, i8*)
declare i32 @ls_variant_tag(i8*)
declare i8* @ls_variant_payload(i8*)

%ls.tuple.1 = type { i32, i8* }
define i32 @main() {
entry:
  %_t1 = call i8* @ls_variant_mk(i32 0, i8* null)
  %_t2_pk0 = insertvalue %ls.tuple.1 undef, i32 1, 0
  %_t2 = insertvalue %ls.tuple.1 %_t2_pk0, i8* %_t1, 1
  %_t3 = call i8* @ls_malloc(i64 16)
  %_t3_bptr = bitcast i8* %_t3 to %ls.tuple.1*
  store %ls.tuple.1 %_t2, %ls.tuple.1* %_t3_bptr
  %_t4 = call i8* @ls_variant_mk(i32 1, i8* %_t3)
  %x = bitcast i8* %_t4 to i8*
  %_t5 = call i32 @ls_variant_tag(i8* %x)
  %_t6 = icmp eq i32 %_t5, 0
  br i1 %_t6, label %swm_2, label %swn_3
swm_2:
  br label %swm_1
swm_1:
  %_t11 = phi i32 [ 0, %swm_2 ], [ 1, %swm_4 ]
  %_t12 = call i8* @ls_int_to_str(i32 %_t11)
  call void @ls_println(i8* %_t12)
  ret i32 0
swn_3:
  %_t7 = call i32 @ls_variant_tag(i8* %x)
  %_t8 = icmp eq i32 %_t7, 1
  %_t9 = call i8* @ls_variant_payload(i8* %x)
  %_t10_uptr = bitcast i8* %_t9 to %ls.tuple.1*
  %_t10 = load %ls.tuple.1, %ls.tuple.1* %_t10_uptr
  br i1 %_t8, label %swm_4, label %swf_5
swm_4:
  br label %swm_1
swf_5:
  call void @ls_abort()
  unreachable
}
