let () = println (1 == 1)
let () = println (1 == 2)
let () = println ("hello" == "hello")
let () = println ("hello" == "world")
let () = println (true == true)
let () = println (true == false)
let () = println ('a' == 'a')
let () = println ('a' == 'b')
