; Generated by LambdaScript compiler (Min_ir → LLVM IR)
source_filename = "lambdascript"

declare void @ls_print(i8*)
declare void @ls_println(i8*)
declare i8* @ls_int_to_str(i32)

define i32 @add(i32 %x, i32 %y) {
entry:
  %_t1 = add nsw i32 %x, %y
  ret i32 %_t1
}

define i32 @factorial(i32 %n) {
entry:
  %_t4 = icmp eq i32 %n, 0
  br i1 %_t4, label %then_1, label %else_2
then_1:
  br label %merge_3
merge_3:
  %_t8 = phi i32 [ 1, %then_1 ], [ %_t7, %else_2 ]
  ret i32 %_t8
else_2:
  %_t5 = sub nsw i32 %n, 1
  %_t6 = call i32 @factorial(i32 %_t5)
  %_t7 = mul nsw i32 %n, %_t6
  br label %merge_3
}

define i32 @main() {
entry:
  %_t2 = call i32 @add(i32 10, i32 20)
  %result = add nsw i32 %_t2, 0
  %_t3 = call i8* @ls_int_to_str(i32 %result)
  call void @ls_println(i8* %_t3)
  %_t9 = call i32 @factorial(i32 5)
  %fact5 = add nsw i32 %_t9, 0
  %_t10 = call i8* @ls_int_to_str(i32 %fact5)
  call void @ls_println(i8* %_t10)
  ret i32 0
}
