; Generated by LambdaScript compiler (Min_ir → LLVM IR)
source_filename = "lambdascript"

declare void @ls_print(i8*)
declare void @ls_println(i8*)
declare i8* @ls_int_to_str(i32)

define i32 @add(i32 %x, i32 %y, i1 %bb) {
entry:
  br i1 %bb, label %then_1, label %else_2
then_1:
  %_t1 = add nsw i32 %x, %y
  br label %merge_3
merge_3:
  %_t3 = phi i32 [ %_t1, %then_1 ], [ %_t2, %else_2 ]
  ret i32 %_t3
else_2:
  %_t2 = sub nsw i32 %x, %y
  br label %merge_3
}

define i32 @main() {
entry:
  %_t4 = call i32 @add(i32 1, i32 2, i1 false)
  %res = add nsw i32 %_t4, 0
  %_t5 = call i8* @ls_int_to_str(i32 %res)
  call void @ls_println(i8* %_t5)
  ret i32 0
}
