; Generated by LambdaScript compiler (Min_ir → LLVM IR)
source_filename = "lambdascript"

%ls.clos = type { i8*, i8* }

declare void @ls_print(i8*)
declare void @ls_println(i8*)
declare i8* @ls_int_to_str(i32)
declare i8* @ls_str_concat(i8*, i8*)
declare i8* @ls_malloc(i64)
declare i8* @ls_mkclos(i8*, i8*)

%ls.tuple.1 = type { i32, i32 }
define i32 @tuple_fst__lsm963247424(%ls.tuple.1 %p) {
entry:
  %_t1 = extractvalue %ls.tuple.1 %p, 0
  %_t2 = extractvalue %ls.tuple.1 %p, 1
  ret i32 %_t1
}

define i32 @tuple_snd__lsm963247424(%ls.tuple.1 %p) {
entry:
  %_t3 = extractvalue %ls.tuple.1 %p, 0
  %_t4 = extractvalue %ls.tuple.1 %p, 1
  ret i32 %_t4
}

define i32 @main() {
entry:
  %_t5_pk0 = insertvalue %ls.tuple.1 undef, i32 5, 0
  %_t5 = insertvalue %ls.tuple.1 %_t5_pk0, i32 10, 1
  %_t6 = call i32 @tuple_fst__lsm963247424(%ls.tuple.1 %_t5)
  %_t7 = call i8* @ls_int_to_str(i32 %_t6)
  call void @ls_println(i8* %_t7)
  %_t8_pk0 = insertvalue %ls.tuple.1 undef, i32 5, 0
  %_t8 = insertvalue %ls.tuple.1 %_t8_pk0, i32 10, 1
  %_t9 = call i32 @tuple_snd__lsm963247424(%ls.tuple.1 %_t8)
  %_t10 = call i8* @ls_int_to_str(i32 %_t9)
  call void @ls_println(i8* %_t10)
  ret i32 0
}
